### PR TITLE
fix macos mcumgr in  helper_functions.py

### LINKED ISSUE #5: [mcumgr] Automatic download for mcumgr in MAC not working
**Description**

While working with the Tutorials with some students, I had one of them with a MAC computer that was not able to flash the twist board. 

**Fix**

We had to manually download  `https://github.com/owntech-foundation/mcumgr/releases/download/v0.4/mcumgr-mac`
and place it in `owntech/third_parties`. 

**To do**

Try to reproduce this problem on another MAC and figure out why it did not work.

### PR DESCRIPTION
**Pull request by guigur**
fix #5 
this replaces the legacy `urlretrieve` for downloading external resources
This needs to be tested on Win and Linux

### CODE REVIEW

**Comment by guigur** [comment]
@jalinei up

**Comment by guigur** [comment]
up

**Comment by jalinei** [comment]
@guigur maybe the easy way is to put the macos fix in a 
```if platform.system() == 'Darwin'```
This way we are sure that it works as before for Win and Linux ?

**Comment by luizvilla** [comment]
I have tested with Linux and Windows. 
I have successfully erased the mcumgr from the owntech/third_party folder and it was automatically replaced. Build and upload were working normally. 
Merging.

**Pull request merged**
